In [1]:
import pandas as pd
import numpy as np

In [10]:
labeled_data = pd.read_csv('data/labeled_data.csv', index_col=0)

moldset_labeled_cn7 = pd.read_csv('data/moldset_labeled_cn7.csv', index_col=0)
moldset_labeled_rg3 = pd.read_csv('data/moldset_labeled_rg3.csv', index_col=0)
moldset_labeled = pd.read_csv('data/moldset_labeled.csv', index_col=0)

moldset_unlabeled_cn7 = pd.read_csv('data/moldset_unlabeled_cn7.csv', index_col=0)
moldset_unlabeled_rg3 = pd.read_csv('data/moldset_unlabeled_rg3.csv', index_col=0)

supervised_label_cn7 = pd.read_csv('data/supervised_label_cn7.csv', index_col=0)

unlabeled_data = pd.read_csv('data/unlabeled_data.csv', index_col=0)

In [11]:
print(labeled_data.shape)

print(moldset_labeled_cn7.shape)
print(moldset_labeled_rg3.shape)
print(moldset_labeled.shape)

print(moldset_unlabeled_cn7.shape)
print(moldset_unlabeled_rg3.shape)

print(supervised_label_cn7.shape)

print(unlabeled_data.shape)

(7996, 44)
(1211, 25)
(1182, 25)
(2607, 46)
(35239, 24)
(35941, 24)
(6736, 25)
(795315, 45)

In [12]:
display(labeled_data.head())

display(moldset_labeled_cn7.head())
display(moldset_labeled_rg3.head())
display(moldset_labeled.head())

display(moldset_unlabeled_cn7.head())
display(moldset_unlabeled_rg3.head())

display(supervised_label_cn7.head())

display(unlabeled_data.head())

,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,Filling_Time,...,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
_id,,,,,,,,,,,,,,,,,,,,,
5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,4.47,...,24.799999,27.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,4.48,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,4.48,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,4.48,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,4.48,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,PassOrFail,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,...,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,0,1.679123,1.491397,-0.478017,0.361047,0.97858,-0.711164,1.532018,0.0,-1.152398,...,-0.533773,0.729073,-1.598068,-0.672350,-1.536620,0.008133,-1.352970,-1.780463,1.023094,1.287574
1,0,2.080358,1.894372,-0.527100,1.886261,0.97858,-0.711164,1.471608,0.0,-1.347095,...,-0.533773,0.056153,0.622557,0.914107,0.504051,-0.915098,-2.263700,-0.874018,1.023094,1.337339
2,0,2.080358,1.894372,-0.527100,1.886261,0.97858,-0.711164,1.471608,0.0,-1.347095,...,-0.533773,0.056153,0.622557,0.914107,0.504051,-0.915098,-2.263700,-0.874018,1.023094,1.337339
3,0,1.679123,1.894372,-0.527100,1.377857,0.97858,1.202502,1.471608,0.0,-1.347095,...,-0.533773,0.729073,-0.765355,1.231418,0.886706,-0.299626,0.013158,-1.176164,1.166162,1.337339
4,0,1.679123,1.894372,-0.527100,1.377857,0.97858,1.202502,1.471608,0.0,-1.347095,...,-0.533773,0.729073,-0.765355,1.231418,0.886706,-0.299626,0.013158,-1.176164,1.166162,1.337339

,PassOrFail,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,...,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
1211,0,-0.029099,-1.192531,1.977737,0.249511,1.033078,2.867608,-1.755816,0.0,2.187583,...,-1.306878,0.096629,-0.496175,-0.002081,0.047749,0.282727,-0.354184,0.183232,-1.393485,-1.576042
1212,0,-0.029099,-1.192531,1.977737,0.249511,1.033078,2.867608,-1.755816,0.0,2.187583,...,-1.306878,0.096629,-0.496175,-0.002081,0.047749,0.282727,-0.354184,0.183232,-1.393485,-1.576042
1213,0,-0.029099,-1.192531,1.528778,0.249511,1.033078,2.075089,-0.192928,0.0,2.187583,...,-0.841877,0.562844,1.442567,-0.002081,0.340262,1.850096,-0.851297,0.183232,-1.535968,-1.576042
1214,0,-0.029099,-1.192531,1.528778,0.249511,1.033078,2.075089,-0.192928,0.0,2.187583,...,-0.841877,0.562844,1.442567,-0.002081,0.340262,1.850096,-0.851297,0.183232,-1.535968,-1.576042
1215,0,-0.029099,-1.192531,0.630880,-0.298708,1.033078,1.277707,-1.755816,0.0,1.402554,...,-1.539374,1.262095,-0.253813,-0.002081,0.925242,0.282727,-1.348485,0.284910,-1.535968,-1.576042

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NO,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,...,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,86141AA000,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,0,NaN,...,24.799999,27.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,86141AA000,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,0,NaN,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,86131AA000,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,0,NaN,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,86131AA000,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,0,NaN,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,86141AA000,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,0,NaN,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,Max_Screw_RPM,...,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
114610,1.346829,-2.768862,0.961909,1.843294,1.029767,1.031111,0.849819,0.861854,2.489188,1.025136,...,0.221579,1.015093,0.919876,0.846380,0.637023,2.099671,1.025241,-0.551566,0.756435,0.600810
114688,1.360046,-2.720306,0.963280,1.847956,1.029767,1.031048,0.863559,0.861854,2.446877,1.025136,...,0.228419,1.020221,0.988615,0.874453,0.703109,2.099671,1.074495,-0.503460,0.818567,0.700620
114919,1.355641,-2.720306,0.966020,1.843294,1.029767,1.031080,0.864246,0.861854,2.446877,1.025136,...,0.221579,1.014360,0.862594,0.874453,0.637023,2.293882,0.975987,-0.599672,0.694303,0.574194
115304,1.360046,-2.720306,0.960539,1.843294,1.029767,1.031143,0.864246,0.861854,2.455339,1.025136,...,0.221579,1.017290,0.919876,0.944634,0.785717,2.099671,1.058077,-0.599672,0.531206,0.394536
115582,1.360046,-2.720306,0.967391,1.847956,1.029767,1.031048,0.864933,0.861854,2.446877,1.018644,...,0.221579,1.018756,0.851137,0.916562,0.670066,2.177355,0.992405,-0.599672,0.585571,0.434460

,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,Max_Screw_RPM,...,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
119515,0.90919,1.662808,-1.131352,-1.174407,-1.262902,-1.314850,-1.026514,1.362091,-1.203070,-1.179145,...,-1.154268,-1.310547,-0.666957,-0.395393,0.088306,0.041839,0.945920,0.087427,-1.276966,-1.225083
119547,0.90919,1.662808,-1.131352,-1.174407,-1.262902,-1.314850,-1.026514,1.362091,-1.200666,-1.179145,...,-1.154268,-1.310547,-0.674680,-0.403577,0.078025,0.029691,0.925301,0.107476,-1.276966,-1.225083
119618,0.90919,1.662808,-1.147464,-1.174407,-1.262902,-1.315176,-1.026514,1.362091,-1.200666,-1.179145,...,-1.154268,-1.310547,-0.636064,-0.395393,0.078025,0.066135,0.904682,0.107476,-1.276966,-1.225083
119781,0.90919,1.662808,-1.131352,-1.174407,-1.262902,-1.314850,-1.026514,1.362091,-1.193454,-1.179145,...,-1.154268,-1.310547,-0.674680,-0.395393,0.067743,0.029691,0.863445,0.127524,-1.276966,-1.225083
120044,0.90919,1.662808,-1.131352,-1.174407,-1.262902,-1.314850,-1.026514,1.362091,-1.159797,-1.179145,...,-1.154268,-1.310547,-0.674680,-0.395393,0.088306,0.041839,0.945920,0.147573,-1.276966,-1.225083

,PassOrFail,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Plasticizing_Position,Clamp_Open_Position,Max_Injection_Speed,...,Average_Back_Pressure,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,0,9.60,4.48,16.91,59.580002,7.13,653.409973,68.839996,647.98999,55.299999,...,59.299999,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,67.199997,24.799999,27.6
1,0,9.59,4.48,16.91,59.560001,7.13,653.419983,68.839996,647.98999,55.299999,...,59.299999,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,66.900002,25.000000,27.6
2,0,9.58,4.46,16.90,59.580002,7.13,653.409973,68.839996,647.98999,55.599998,...,59.400002,276.299988,275.299988,275.200012,271.399994,255.000000,230.000000,67.500000,25.000000,27.6
3,0,9.58,4.46,16.92,59.560001,7.13,653.409973,68.849998,647.98999,55.500000,...,59.299999,275.799988,275.399994,275.000000,271.299988,255.000000,230.000000,67.000000,25.000000,27.6
4,0,9.57,4.45,16.91,59.520000,7.14,653.409973,68.830002,647.98999,55.700001,...,59.099998,275.700012,274.899994,274.799988,270.799988,255.399994,230.100006,66.699997,24.799999,27.5

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NO,PART_NAME,EQUIP_CD,EQUIP_NAME,ERR_FACT_QTY,Injection_Time,...,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
0,5f9136166e37704af878240e,2020-01-02 00:59:22,2020-01-02 오전 12:00:00,2,87285Q5000,"SP2 CVR ROOF RACK CTR, RH",S01,1800TON-우진,11,3.18,...,0.0,0.0,0,0,0,0,0,0,0,0
1,5f9136166e37704af878240f,2020-01-02 01:01:01,2020-01-02 오전 12:00:00,1,87275Q5000,"SP2 CVR ROOF RACK CTR, LH",S01,1800TON-우진,11,16.29,...,0.0,0.0,0,0,0,0,0,0,0,0
2,5f9136166e37704af8782410,2020-01-02 01:01:01,2020-01-02 오전 12:00:00,2,87285Q5000,"SP2 CVR ROOF RACK CTR, RH",S01,1800TON-우진,11,16.29,...,0.0,0.0,0,0,0,0,0,0,0,0
3,5f9136166e37704af8782411,2020-01-02 01:02:24,2020-01-02 오전 12:00:00,1,87275Q5000,"SP2 CVR ROOF RACK CTR, LH",S01,1800TON-우진,11,16.28,...,0.0,0.0,0,0,0,0,0,0,0,0
4,5f9136166e37704af8782412,2020-01-02 01:02:24,2020-01-02 오전 12:00:00,2,87285Q5000,"SP2 CVR ROOF RACK CTR, RH",S01,1800TON-우진,11,16.28,...,0.0,0.0,0,0,0,0,0,0,0,0

In [15]:
print("=" * 60)
print("labeled_data")
print(labeled_data.info(), end='\n\n')

print("=" * 60)
print("moldset_labeled_cn7")
print(moldset_labeled_cn7.info(), end='\n\n')

print("=" * 60)
print("moldset_labeled_rg3")
print(moldset_labeled_rg3.info(), end='\n\n')

print("=" * 60)
print("moldset_labeled")
print(moldset_labeled.info(), end='\n\n')

print("=" * 60)
print("moldset_unlabeled_cn7")
print(moldset_unlabeled_cn7.info(), end='\n\n')

print("=" * 60)
print("moldset_unlabeled_rg3")
print(moldset_unlabeled_rg3.info(), end='\n\n')

print("=" * 60)
print("supervised_label_cn7")
print(supervised_label_cn7.info(), end='\n\n')

print("=" * 60)
print("unlabeled_data")
print(unlabeled_data.info(), end='\n\n')

============================================================
labeled_data
<class 'pandas.core.frame.DataFrame'>
Index: 7996 entries, 5f8928bb9c0189cc666ef19b to 5fa112bc9c0189cc66dac23a
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TimeStamp                 7996 non-null   object
 1   PART_FACT_PLAN_DATE       7996 non-null   object
 2   PART_FACT_SERIAL          7996 non-null   int64
 3   PART_NAME                 7996 non-null   object
 4   EQUIP_CD                  7996 non-null   object
 5   EQUIP_NAME                7996 non-null   object
 6   PassOrFail                7996 non-null   object
 7   Reason                    71 non-null     object
 8   Injection_Time            7996 non-null   float64
 9   Filling_Time              7996 non-null   float64
 10  Plasticizing_Time         7996 non-null   float64
 11  Cycle_Time                7996 non-null   float64
 12  Clamp_Close_Time          7996 non-null   float64
 13  Cushion_Position          7996 non-null   float64
 14  Switch_Over_Position      7996 non-null   float64
 15  Plasticizing_Position     7996 non-null   float64
 16  Clamp_Open_Position       7996 non-null   float64
 17  Max_Injection_Speed       7996 non-null   float64
 18  Max_Screw_RPM             7996 non-null   float64
 19  Average_Screw_RPM         7996 non-null   float64
 20  Max_Injection_Pressure    7996 non-null   float64
 21  Max_Switch_Over_Pressure  7996 non-null   float64
 22  Max_Back_Pressure         7996 non-null   float64
 23  Average_Back_Pressure     7996 non-null   float64
 24  Barrel_Temperature_1      7996 non-null   float64
 25  Barrel_Temperature_2      7996 non-null   float64
 26  Barrel_Temperature_3      7996 non-null   float64
 27  Barrel_Temperature_4      7996 non-null   float64
 28  Barrel_Temperature_5      7996 non-null   float64
 29  Barrel_Temperature_6      7996 non-null   float64
 30  Barrel_Temperature_7      7996 non-null   float64
 31  Hopper_Temperature        7996 non-null   float64
 32  Mold_Temperature_1        7996 non-null   float64
 33  Mold_Temperature_2        7996 non-null   float64
 34  Mold_Temperature_3        7996 non-null   float64
 35  Mold_Temperature_4        7996 non-null   float64
 36  Mold_Temperature_5        7996 non-null   float64
 37  Mold_Temperature_6        7996 non-null   float64
 38  Mold_Temperature_7        7996 non-null   float64
 39  Mold_Temperature_8        7996 non-null   float64
 40  Mold_Temperature_9        7996 non-null   float64
 41  Mold_Temperature_10       7996 non-null   float64
 42  Mold_Temperature_11       7996 non-null   float64
 43  Mold_Temperature_12       7996 non-null   float64
dtypes: float64(36), int64(1), object(7)
memory usage: 2.7+ MB
None

============================================================
moldset_labeled_cn7
<class 'pandas.core.frame.DataFrame'>
Index: 1211 entries, 0 to 1210
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   PassOrFail                1211 non-null   int64
 1   Injection_Time            1211 non-null   float64
 2   Filling_Time              1211 non-null   float64
 3   Plasticizing_Time         1211 non-null   float64
 4   Cycle_Time                1211 non-null   float64
 5   Clamp_Close_Time          1211 non-null   float64
 6   Cushion_Position          1211 non-null   float64
 7   Plasticizing_Position     1211 non-null   float64
 8   Clamp_Open_Position       1211 non-null   float64
 9   Max_Injection_Speed       1211 non-null   float64
 10  Max_Screw_RPM             1211 non-null   float64
 11  Average_Screw_RPM         1211 non-null   float64
 12  Max_Injection_Pressure    1211 non-null   float64
 13  Max_Switch_Over_Pressure  1211 non-null   float64
 14  Max_Back_Pressure         1211 non-null   float64
 15  Average_Back_Pressure     1211 non-null   float64
 16  Barrel_Temperature_1      1211 non-null   float64
 17  Barrel_Temperature_2      1211 non-null   float64
 18  Barrel_Temperature_3      1211 non-null   float64
 19  Barrel_Temperature_4      1211 non-null   float64
 20  Barrel_Temperature_5      1211 non-null   float64
 21  Barrel_Temperature_6      1211 non-null   float64
 22  Hopper_Temperature        1211 non-null   float64
 23  Mold_Temperature_3        1211 non-null   float64
 24  Mold_Temperature_4        1211 non-null   float64
dtypes: float64(24), int64(1)
memory usage: 246.0 KB
None

============================================================
moldset_labeled_rg3
<class 'pandas.core.frame.DataFrame'>
Index: 1182 entries, 1211 to 2392
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   PassOrFail                1182 non-null   int64
 1   Injection_Time            1182 non-null   float64
 2   Filling_Time              1182 non-null   float64
 3   Plasticizing_Time         1182 non-null   float64
 4   Cycle_Time                1182 non-null   float64
 5   Clamp_Close_Time          1182 non-null   float64
 6   Cushion_Position          1182 non-null   float64
 7   Plasticizing_Position     1182 non-null   float64
 8   Clamp_Open_Position       1182 non-null   float64
 9   Max_Injection_Speed       1182 non-null   float64
 10  Max_Screw_RPM             1182 non-null   float64
 11  Average_Screw_RPM         1182 non-null   float64
 12  Max_Injection_Pressure    1182 non-null   float64
 13  Max_Switch_Over_Pressure  1182 non-null   float64
 14  Max_Back_Pressure         1182 non-null   float64
 15  Average_Back_Pressure     1182 non-null   float64
 16  Barrel_Temperature_1      1182 non-null   float64
 17  Barrel_Temperature_2      1182 non-null   float64
 18  Barrel_Temperature_3      1182 non-null   float64
 19  Barrel_Temperature_4      1182 non-null   float64
 20  Barrel_Temperature_5      1182 non-null   float64
 21  Barrel_Temperature_6      1182 non-null   float64
 22  Hopper_Temperature        1182 non-null   float64
 23  Mold_Temperature_3        1182 non-null   float64
 24  Mold_Temperature_4        1182 non-null   float64
dtypes: float64(24), int64(1)
memory usage: 240.1 KB
None

============================================================
moldset_labeled
<class 'pandas.core.frame.DataFrame'>
Index: 2607 entries, 0 to 2392
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _id                       2607 non-null   object
 1   TimeStamp                 2607 non-null   object
 2   PART_FACT_PLAN_DATE       2607 non-null   object
 3   PART_FACT_SERIAL          2607 non-null   int64
 4   PART_NO                   2607 non-null   object
 5   PART_NAME                 2607 non-null   object
 6   EQUIP_CD                  2607 non-null   object
 7   EQUIP_NAME                2607 non-null   object
 8   PassOrFail                2607 non-null   int64
 9   Reason                    52 non-null     object
 10  Injection_Time            2607 non-null   float64
 11  Filling_Time              2607 non-null   float64
 12  Plasticizing_Time         2607 non-null   float64
 13  Cycle_Time                2607 non-null   float64
 14  Clamp_Close_Time          2607 non-null   float64
 15  Cushion_Position          2607 non-null   float64
 16  Switch_Over_Position      2607 non-null   float64
 17  Plasticizing_Position     2607 non-null   float64
 18  Clamp_Open_Position       2607 non-null   float64
 19  Max_Injection_Speed       2607 non-null   float64
 20  Max_Screw_RPM             2607 non-null   float64
 21  Average_Screw_RPM         2607 non-null   float64
 22  Max_Injection_Pressure    2607 non-null   float64
 23  Max_Switch_Over_Pressure  2607 non-null   float64
 24  Max_Back_Pressure         2607 non-null   float64
 25  Average_Back_Pressure     2607 non-null   float64
 26  Barrel_Temperature_1      2607 non-null   float64
 27  Barrel_Temperature_2      2607 non-null   float64
 28  Barrel_Temperature_3      2607 non-null   float64
 29  Barrel_Temperature_4      2607 non-null   float64
 30  Barrel_Temperature_5      2607 non-null   float64
 31  Barrel_Temperature_6      2607 non-null   float64
 32  Barrel_Temperature_7      2607 non-null   float64
 33  Hopper_Temperature        2607 non-null   float64
 34  Mold_Temperature_1        2607 non-null   float64
 35  Mold_Temperature_2        2607 non-null   float64
 36  Mold_Temperature_3        2607 non-null   float64
 37  Mold_Temperature_4        2607 non-null   float64
 38  Mold_Temperature_5        2607 non-null   float64
 39  Mold_Temperature_6        2607 non-null   float64
 40  Mold_Temperature_7        2607 non-null   float64
 41  Mold_Temperature_8        2607 non-null   float64
 42  Mold_Temperature_9        2607 non-null   float64
 43  Mold_Temperature_10       2607 non-null   float64
 44  Mold_Temperature_11       2607 non-null   float64
 45  Mold_Temperature_12       2607 non-null   float64
dtypes: float64(36), int64(2), object(8)
memory usage: 957.3+ KB
None

============================================================
moldset_unlabeled_cn7
<class 'pandas.core.frame.DataFrame'>
Index: 35239 entries, 114610 to 777220
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Injection_Time            35239 non-null  float64
 1   Filling_Time              35239 non-null  float64
 2   Plasticizing_Time         35239 non-null  float64
 3   Cycle_Time                35239 non-null  float64
 4   Clamp_Close_Time          35239 non-null  float64
 5   Cushion_Position          35239 non-null  float64
 6   Plasticizing_Position     35239 non-null  float64
 7   Clamp_Open_Position       35239 non-null  float64
 8   Max_Injection_Speed       35239 non-null  float64
 9   Max_Screw_RPM             35239 non-null  float64
 10  Average_Screw_RPM         35239 non-null  float64
 11  Max_Injection_Pressure    35239 non-null  float64
 12  Max_Switch_Over_Pressure  35239 non-null  float64
 13  Max_Back_Pressure         35239 non-null  float64
 14  Average_Back_Pressure     35239 non-null  float64
 15  Barrel_Temperature_1      35239 non-null  float64
 16  Barrel_Temperature_2      35239 non-null  float64
 17  Barrel_Temperature_3      35239 non-null  float64
 18  Barrel_Temperature_4      35239 non-null  float64
 19  Barrel_Temperature_5      35239 non-null  float64
 20  Barrel_Temperature_6      35239 non-null  float64
 21  Hopper_Temperature        35239 non-null  float64
 22  Mold_Temperature_3        35239 non-null  float64
 23  Mold_Temperature_4        35239 non-null  float64
dtypes: float64(24)
memory usage: 6.7 MB
None

============================================================
moldset_unlabeled_rg3
<class 'pandas.core.frame.DataFrame'>
Index: 35941 entries, 119515 to 795309
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Injection_Time            35941 non-null  float64
 1   Filling_Time              35941 non-null  float64
 2   Plasticizing_Time         35941 non-null  float64
 3   Cycle_Time                35941 non-null  float64
 4   Clamp_Close_Time          35941 non-null  float64
 5   Cushion_Position          35941 non-null  float64
 6   Plasticizing_Position     35941 non-null  float64
 7   Clamp_Open_Position       35941 non-null  float64
 8   Max_Injection_Speed       35941 non-null  float64
 9   Max_Screw_RPM             35941 non-null  float64
 10  Average_Screw_RPM         35941 non-null  float64
 11  Max_Injection_Pressure    35941 non-null  float64
 12  Max_Switch_Over_Pressure  35941 non-null  float64
 13  Max_Back_Pressure         35941 non-null  float64
 14  Average_Back_Pressure     35941 non-null  float64
 15  Barrel_Temperature_1      35941 non-null  float64
 16  Barrel_Temperature_2      35941 non-null  float64
 17  Barrel_Temperature_3      35941 non-null  float64
 18  Barrel_Temperature_4      35941 non-null  float64
 19  Barrel_Temperature_5      35941 non-null  float64
 20  Barrel_Temperature_6      35941 non-null  float64
 21  Hopper_Temperature        35941 non-null  float64
 22  Mold_Temperature_3        35941 non-null  float64
 23  Mold_Temperature_4        35941 non-null  float64
dtypes: float64(24)
memory usage: 6.9 MB
None

============================================================
supervised_label_cn7
<class 'pandas.core.frame.DataFrame'>
Index: 6736 entries, 0 to 6735
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   PassOrFail                6736 non-null   int64
 1   Injection_Time            6736 non-null   float64
 2   Filling_Time              6736 non-null   float64
 3   Plasticizing_Time         6736 non-null   float64
 4   Cycle_Time                6736 non-null   float64
 5   Clamp_Close_Time          6736 non-null   float64
 6   Cushion_Position          6736 non-null   float64
 7   Plasticizing_Position     6736 non-null   float64
 8   Clamp_Open_Position       6736 non-null   float64
 9   Max_Injection_Speed       6736 non-null   float64
 10  Max_Screw_RPM             6736 non-null   float64
 11  Average_Screw_RPM         6736 non-null   float64
 12  Max_Injection_Pressure    6736 non-null   float64
 13  Max_Switch_Over_Pressure  6736 non-null   float64
 14  Max_Back_Pressure         6736 non-null   float64
 15  Average_Back_Pressure     6736 non-null   float64
 16  Barrel_Temperature_1      6736 non-null   float64
 17  Barrel_Temperature_2      6736 non-null   float64
 18  Barrel_Temperature_3      6736 non-null   float64
 19  Barrel_Temperature_4      6736 non-null   float64
 20  Barrel_Temperature_5      6736 non-null   float64
 21  Barrel_Temperature_6      6736 non-null   float64
 22  Hopper_Temperature        6736 non-null   float64
 23  Mold_Temperature_3        6736 non-null   float64
 24  Mold_Temperature_4        6736 non-null   float64
dtypes: float64(24), int64(1)
memory usage: 1.3 MB
None

============================================================
unlabeled_data
<class 'pandas.core.frame.DataFrame'>
Index: 795315 entries, 0 to 795314
Data columns (total 45 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   _id                       795315 non-null  object
 1   TimeStamp                 795315 non-null  object
 2   PART_FACT_PLAN_DATE       795315 non-null  object
 3   PART_FACT_SERIAL          795315 non-null  int64
 4   PART_NO                   795315 non-null  object
 5   PART_NAME                 795315 non-null  object
 6   EQUIP_CD                  795315 non-null  object
 7   EQUIP_NAME                795315 non-null  object
 8   ERR_FACT_QTY              795315 non-null  int64
 9   Injection_Time            795315 non-null  float64
 10  Filling_Time              795315 non-null  float64
 11  Plasticizing_Time         795315 non-null  float64
 12  Cycle_Time                795315 non-null  float64
 13  Clamp_Close_Time          795315 non-null  float64
 14  Cushion_Position          795315 non-null  float64
 15  Switch_Over_Position      795315 non-null  float64
 16  Plasticizing_Position     795315 non-null  float64
 17  Clamp_Open_Position       795315 non-null  float64
 18  Max_Injection_Speed       795315 non-null  float64
 19  Max_Screw_RPM             795315 non-null  float64
 20  Average_Screw_RPM         795315 non-null  float64
 21  Max_Injection_Pressure    795315 non-null  float64
 22  Max_Switch_Over_Pressure  795315 non-null  float64
 23  Max_Back_Pressure         795315 non-null  float64
 24  Average_Back_Pressure     795315 non-null  float64
 25  Barrel_Temperature_1      795315 non-null  float64
 26  Barrel_Temperature_2      795315 non-null  float64
 27  Barrel_Temperature_3      795315 non-null  float64
 28  Barrel_Temperature_4      795315 non-null  float64
 29  Barrel_Temperature_5      795315 non-null  float64
 30  Barrel_Temperature_6      795315 non-null  float64
 31  Barrel_Temperature_7      795315 non-null  float64
 32  Hopper_Temperature        795315 non-null  float64
 33  Mold_Temperature_1        795315 non-null  int64
 34  Mold_Temperature_2        795315 non-null  int64
 35  Mold_Temperature_3        795315 non-null  float64
 36  Mold_Temperature_4        795315 non-null  float64
 37  Mold_Temperature_5        795315 non-null  int64
 38  Mold_Temperature_6        795315 non-null  int64
 39  Mold_Temperature_7        795315 non-null  int64
 40  Mold_Temperature_8        795315 non-null  int64
 41  Mold_Temperature_9        795315 non-null  int64
 42  Mold_Temperature_10       795315 non-null  int64
 43  Mold_Temperature_11       795315 non-null  int64
 44  Mold_Temperature_12       795315 non-null  int64
dtypes: float64(26), int64(12), object(7)
memory usage: 279.1+ MB
None